[package]
name = "bad-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
get_str = { path = "../get_str" }

[dev-dependencies]
get_str = { path = "../get_str" , features = ["test"]}
